version: '3.8'

services:
  loki:
    image: grafana/loki:3.4.1
    ports:
      - "3100:3100"
    volumes:
      - type: bind
        source: ./loki-config.yaml
        target: /etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:3.4.1
    volumes:
      - type: bind
        source: ./promtail-config.yaml
        target: /etc/promtail/promtail-config.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:11.3.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - type: bind
        source: ./grafana-datasources.yaml
        target: /etc/grafana/provisioning/datasources/datasources.yaml
    networks:
      - monitoring

volumes:
  grafana-data:

networks:
  monitoring:
    driver: bridge