name: CI/CD for ASP.NET Core Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  # Only trigger when changes are made to the backend directory

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install sshpass for SSH password authentication
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      # Deploy to VPS via SSH
      - name: Deploy to VPS
        env:
          VPS_HOST: 42.96.13.119
          VPS_PASSWORD: 0o4bzIZR
          PROJECT_PATH: /server/Langstudio/
        run: |
          sshpass -p "$VPS_PASSWORD" ssh -p 26266 -o StrictHostKeyChecking=no root@42.96.13.119 << 'EOF'
            cd /server/Langstudio
            # Pull latest code
            git reset --hard HEAD
            git clean -fd
            git pull origin main

            cd backend

            # Update database
            dotnet ef database update || {
              echo "Database update failed, dropping and retrying..."
              dotnet ef migrations add "Migration_$(date +%s)"
              dotnet ef database update
            }

            # Publish project
            dotnet publish -c Release -o publish

            # Sync files to production directory
            rsync -av --delete ./publish/ /var/www/server/

            # Restart service
            systemctl restart server
          EOF