name: CI/CD for ASP.NET Core Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  # Only trigger when changes are made to the backend directory
      - 'Docker/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Deploy to VPS via SSH using PEM key
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            # Pull latest code
            git reset --hard HEAD
            git clean -fd
            git pull origin main

            cd backend

            # Update database
            dotnet ef database update || {
              echo "Database update failed, dropping and retrying..."
              dotnet ef migrations add "Migration_$(date +%s)"
              dotnet ef database update
            }

            # Publish project
            sudo dotnet publish -c Release -o publish

            # Sync files to production directory
            sudo rsync -av --delete ./publish/ /var/www/server/

            # Restart service
            sudo systemctl restart server
